export const GET_ALL_PRODUCTS= 'GET_ALL_PRODUCTS'
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS'
export const REMOVER_FILTRO = 'REMOVER_FILTRO'
export const AGREGAR_FILTRO = 'AGREGAR_FILTRO'

export const ALL_PRODUCTS= 'ALL_PRODUCTS'

export const CANTIDAD_PRODUCT = 'CANTIDAD_PRODUCT'

export const ADD_PRODUCT ='ADD_PRODUCT'
export const DELETE_PRODUCT ='DELETE_PRODUCT'
export const SHOW_SIDEBAR ='SHOW_SIDEBAR'

export const SUMAR_PRODUCT ='SUMAR_PRODUCT'
export const RESTAR_PRODUCT ='RESTAR_PRODUCT'