//?ALL PRODUCTS
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

//?PRODUCTS DETAILS
export const GET_PRODUCT_BY_ID = "GET_PRODUCTS_BY_ID";
export const CLEAR_PRODUCT_DETAIL = "CLEAR_PRODUCT_DETAIL";

//?FILTERS PRODUCTS
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const REMOVER_FILTRO = "REMOVER_FILTRO";
export const AGREGAR_FILTRO = "AGREGAR_FILTRO";

export const SET_FILTERS = "SET_FILTERS";
export const GET_FILTERS = "GET_FILTERS";

//?CREATE PRODUCT ADMIN
export const ADD_PRODUCT = "ADD_PRODUCT";

//?DELETE PRODUCT ADMIN
export const DELETE_PRODUCT = "DELETE_PRODUCT";

//?EDIT PRODUCT ADMIN
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const ADD_IMG = "ADD_IMG";
export const REMOVE_IMG = "REMOVE_IMG";

export const PRODUCT_TO_EDIT = "PRODUCT_TO_EDIT";
export const CLEAR_PRODUCT_TO_EDIT = "CLEAR_PRODUCT_TO_EDIT";

//?SIDEBAR CLIENT
export const SHOW_SIDEBAR = "SHOW_SIDEBAR";
export const DISABLE_CART = "DISABLE_CART";
export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const DELETE_QUANTITY = "DELETE_QUANTITY";

//?SING IN, UP AND OUT
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const LOG_OUT = "LOG_OUT";

//?USERS
export const GET_ALL_USERS = "GET_ALL_USERS";
export const USER_ADMIN = "USER_ADMIN";
export const USER_BY_ID = "USER_BY_ID";
export const USER_UPDATE = "USER_UPDATE";
export const DELETE_USER = "DELETE_USER";

//?COMENTS
export const POST_COMMENTS = "POST_COMMENTS";
